services:
  app:
    container_name: vaidyalink-app
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/vaidyalink
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      WEB3J_ETHEREUM_ENDPOINT: http://ganache:8545
    depends_on:
      db:
        condition: service_healthy
      ganache:
        condition: service_started
    volumes:
      - .:/app
      - /app/.gradle
      - /app/src:/app/src
    command: ./gradlew bootRun
    networks:
      - app-network

  react:
    container_name: react-frontend
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
    ports:
      - "3000:3000"
    working_dir: /app/frontend
    command: npm start
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: vaidyalink-db
    environment:
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vaidyalink
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 30s
      retries: 3
      timeout: 10s
    networks:
      - app-network

  ganache:
    container_name: vaidyalink-ganache
    image: trufflesuite/ganache-cli:latest
    command: ganache-cli -p 8545 -h 0.0.0.0 -m "vaidyalink" -l 100000000
    ports:
      - "8545:8545"
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
